# No es necesario 'version' en las versiones más recientes de Docker Compose
services:
  postgres_db_multas_app: # Nombre del servicio Docker
    image: postgres:15-alpine # Imagen de PostgreSQL a utilizar
    container_name: pg_multas_notifications_service # Nombre descriptivo para el contenedor
    restart: unless-stopped
    environment:
      POSTGRES_DB: multas # Nombre de la base de datos que se creará
      POSTGRES_USER: postgres # Usuario para la base de datos
      POSTGRES_PASSWORD: 1234 # Contraseña para el usuario
    ports:
      - "5435:5432" # Mapea el puerto 5432 del contenedor al 5435 de tu máquina.
                    # Uso 5435 para evitar conflictos si ya tienes otra instancia de PostgreSQL en 5432.
    volumes:
      - db_data_multas_app:/var/lib/postgresql/data # Volumen para persistir los datos de la BD

volumes:
  db_data_multas_app: # Definición del volumen
    driver: local
